// settlements.js
// translation by Gov. Tarkin

top.settlements = [



 {"title": "d100 Verb", "id":"d100verb_tavernnames", "roll":[
"Ertrinken",
"Hängen",
"Aufstoßen",
"Laufen",
"Gehen",
"Jagen",
"Kämpfen",
"Schwingen",
"Brechen",
"Arbeiten",
"Fermentieren",
"Blühen",
"Sorgen",
"Folgen",
"Fließen",
"Beschweren",
"Stehen",
"Scherzen",
"Lachen",
"Hecheln",
"Einsteigen",
"Faulenzen",
"Schneiden",
"Singen",
"Starren",
"Schwanken",
"Enttäuschen",
"Falten",
"Binden",
"Wickeln",
"Trennen",
"Sehnen",
"Fummeln",
"Fallen",
"Stolpern",
"Sehnen",
"Jammern",
"Fliegen",
"Horten",
"Sorgen",
"Schlagen",
"Blinzeln",
"Weglaufen",
"Gleiten",
"Schnarchen",
"Schnauben",
"Spielen",
"Üben",
"Greifen",
"Verbrennen",
"Flammen",
"Einfrieren",
"Vergiften",
"Begraben",
"Werfen",
"Funkenbilden",
"Dampfen",
"Schmähen",
"Zittern",
"Schnattern ",
"Murmeln",
"Knirschen",
"Pflügen",
"Beißen",
"Heulen",
"Brüllen",
"Schreien",
"Gießen",
"Quietschen",
"Stechen",
"Aufladen",
"Verblassen",
"Stechen",
"Beschweren",
"Stochern",
"Schlucken",
"Saugen",
"Trinken",
"Schleichen",
"Verstecken",
"Hacken",
"Hinken",
"Stolpern",
"Verschieben",
"Gleitend",
"Blenden",
"Töten",
"Knüppeln",
"Zerquetschen",
"Hüpfen",
"Donnern",
"Huschen",
"Weinen",
"Jammern",
"Trauern",
"Verdunkeln",
"Anhäufeln",
"Graben",
"Schleudern",]},
 {"title": "d100 Adjektiv", "id":"d100adjective_tavernnames", "roll":[
"Ruhig",
"Lustig",
"Gut",
"Krumm",
"Weiß",
"Grau",
"Geschwärzt",
"Bedrängt",
"Purpurn",
"Silber",
"Golden",
"Gestört",
"Schmutzig",
"Hässlich",
"Abnormal",
"Gefaltet",
"Glorreich",
"Schön",
"Gut aussehend",
"Faltig",
"Unzufrieden",
"Intelligent",
"Schön",
"Ignorant",
"Senil",
"Sauer",
"Süss",
"Einsam",
"Grün",
"Blind",
"Hungrig",
"Besorgt",
"Gebildet",
"Blöd",
"Ermutigt",
"Ehrenhaft",
"Stinkend",
"Bodenlos",
"Fettig",
"Schlampig",
"Stilvoll",
"Betrübt",
"Verängstigt",
"Gequält",
"Beschämt",
"Schief",
"Gebrochen",
"Schimmelig",
"Klebrig",
"Fermentiert",
"Verdorben",
"Aufwendig",
"Ertrunken",
"Ermordet",
"Verwitwet",
"Gehangen",
"Wütend",
"Lustig",
"Spukig",
"Stark",
"Verwelkt",
"Schön",
"Fromm",
"Süß",
"Geduldig",
"Betrunken",
"Würdig",
"Wohlhabend",
"Abscheulich",
"Schwach",
"Winzig",
"Miniatur",
"Enorm",
"Vergrößert",
"Engagiert",
"Geil",
"Verabscheuungswürdig",
"Obszön",
"Korpulent",
"Heftig",
"Stolpern",
"Defekt",
"Unberührt",
"Sauber",
"Gebrochen",
"Zersplittert",
"Geschmückt",
"Überlegen",
"Makellos",
"Verbreitet",
"Exquisit",
"Elegant",
"Fein",
"Stumpf",
"Spröde",
"Zerbrechlich",
"Weibisch",
"Männlich",
"Träge",]},
 {"title": "d100 Nomen 1A", "id":"d100noun1a_tavernnames", "roll":[
"Reiter",
"Mädchen",
"Magier",
"Bachelor",
"König",
"Magistrat",
"Kriegshäuptling",
"Krieger",
"Stute",
"Wolf",
"Fuchs",
"Löwe",
"Lamm",
"Aufseher",
"Maultier",
"Attentäter",
"Schwertkämpfer",
"Dame",
"Ritter",
"Soldat",
"Magier",
"Hexenmeister",
"Ranger",
"Barde",
"Druide",
"Mönch",
"Paladin",
"Zauberer",
"Schurke",
"Kleriker",
"Bär",
"Kobold",
"Goblin",
"Gnom",
"Halbling",
"Zwerg",
"Dummkopf",
"Jungfrau",
"Horde",
"Knappe",
"Adler",
"Hahn",
"Ferkel",
"Dieb",
"Priester",
"Mönch",
"Schmied",
"Wache",
"Hirsch",
"Hexe",
"Teufel",
"Engel",
"Natter",
"Schlange",
"Ratte",
"Maus",
"Bandit",
"Häuptling",
"Greif",
"Drache",
"Eidechse",
"Pony",
"Baron",
"Färse",
"Stier",
"Hund",
"Ziege",
"Kröte",
"Hengst",
"Monster",
"Ungeziefer",
"Betrachter",
"Affe",
"Elefant",
"Eber",
"Beagle",
"Fledermaus",
"Dämon",
"Wichtel",
"Elf",
"Unhold",
"Geist",
"Hündin",
"Star",
"Minotaurus",
"Barbar",
"Prophet",
"Händler",
"Schuster",
"Einhorn",
"Oger",
"Nymphe",
"Metzger",
"Kapitän",
"Angler",
"Liebhaber",
"Maurer",
"Bastler",
"Wal",   ]},
 {"title": "d100 Nomen 1B", "id":"d100noun1b_tavernnames", "roll":[
"Reiter",
"Mädchen",
"Magier",
"Bachelor",
"König",
"Magistrat",
"Kriegshäuptling",
"Krieger",
"Stute",
"Wolf",
"Fuchs",
"Löwe",
"Lamm",
"Aufseher",
"Maultier",
"Attentäter",
"Schwertkämpfer",
"Dame",
"Ritter",
"Soldat",
"Magier",
"Hexenmeister",
"Ranger",
"Barde",
"Druide",
"Mönch",
"Paladin",
"Zauberer",
"Schurke",
"Kleriker",
"Bär",
"Goblin",
"Kobold",
"Gnom",
"Halbling",
"Zwerg",
"Dummkopf",
"Jungfrau",
"Horde",
"Knappe",
"Adler",
"Hahn",
"Ferkel",
"Dieb",
"Priester",
"Mönch",
"Schmied",
"Wache",
"Hirsch",
"Hexe",
"Teufel",
"Engel",
"Schlange",
"Natter",
"Ratte",
"Maus",
"Bandit",
"Häuptling",
"Greif",
"Drache",
"Eidechse",
"Pony",
"Baron",
"Färse",
"Stier",
"Hund",
"Ziege",
"Kröte",
"Hengst",
"Monster",
"Ungeziefer",
"Betrachter",
"Affe",
"Elefant",
"Eber",
"Beagle",
"Fledermaus",
"Dämon",
"Wichtel",
"Elf",
"Unhold",
"Geist",
"Hündin",
"Star",
"Minotaurus",
"Barbar",
"Prophet",
"Händler",
"Schuster",
"Einhorn",
"Oger",
"Nymphe",
"Metzger",
"Kapitän",
"Angler",
"Liebhaber",
"Maurer",
"Bastler",
"Wal",   ]},
 {"title": "d100 Nomen 2", "id":"d100noun2_tavernnames", "roll":[
"Sattel",
"Gilde",
"Reißzähne",
"Mann",
"Pardon",
"Vergnügen",
"Gürtel",
"Mitarbeiter",
"Schild",
"Prinz",
"Meister",
"Diener",
"Mahlzeit",
"Prinz",
"Gefallen",
"Liebe",
"Wort",
"Schreiber",
"Lehrling",
"Akolyth",
"Kleid",
"Göttin",
"Gott",
"Gold",
"Geldbörse",
"Falle",
"König",
"Sohn",
"Schwester",
"Mutter",
"Tochter",
"Schrei",
"Gekreische",
"Schrank",
"Speisekammer",
"Königin",
"Reichtum",
"Star",
"Leere",
"Frau",
"Mann",
"Hure",
"Metzger",
"Amboss",
"Buch",
"Opfern",
"Rüstung",
"Tasse",
"Topf",
"Herd",
"Schemel",
"Prinzessin",
"Kette",
"Schwert",
"Schweinefleisch",
"Korn",
"Zahn",
"Lanze",
"Axt",
"Scheide",
"Messer",
"Dolch",
"Speer",
"Bogen",
"Armbrust",
"Schlagstock",
"Mitarbeiter",
"Feuer",
"Eis",
"Wind",
"Erde",
"Wasser",
"Stein",
"Kelle",
"Kloster",
"Gefäss",
"Kelch",
"Verlies",
"Lust",
"Laterne",
"Knochen",
"Leben",
"Stein",
"Herrin",
"Verstand",
"Schatz",
"Tausch",
"Waffenmeister",
"Diener",
"Seite",
"Schriftrolle",
"Feder",
"Schatten",
"Freund",
"Labyrinth",
"Berg",
"Hoffnung",
"Boot",
"Handschuh",]},



{"title": "d50 Der Laden verkauft...", "id":"d50theshopsells_shops", "roll":[
"Waffen",
"Rüstung",
"Magische Gegenstände",
"Frisches Essen",
"Eingelegtes Essen",
"Vieh",
"Sklaven",
"Dienstleistungen",
"Vorwiegend Müll",
"Kunstwerke",
"Schmuck",
"Edelsteine ​​und Erze",
"Bergbauwerkzeuge",
"Haushaltsgegenstände",
"Landwirtschaftswerkzeuge",
"Tierfutter",
"Handwerkwerkzeuge",
"Ales und Likör",
"Gegenstände von Interesse aus einer früheren Generation",
"Gegenstände von Interesse aus einem fernen Land",
"Kleidung",
"Gnomische Geräte",
"Zaubertränke",
"Gifte",
"Alchemisches Zubehör",
"Magisches Zubehör",
"Musikinstrumente",
"Stoffe",
"Ein bisschen von allem",
"Gewürze",
"Jagdwerkzeuge",
"Kräuter",
"Heilmittel und Stärkungsmittel",
"Bücher",
"Puppen",
"Spielzeuge",
"Exotische Tiere",
"Pelze und Pelze",
"Illegale Waren",
"Käse",
"Fleisch",
"Rudeltiere",
"Baumaterialien",
"Früchte und Gemüse",
"Zubehör für eine lokale Gilde",
"Lederwaren",
"Gut verarbeitet Gegenstände aus seltenen Metallen",
"Schönheits- und Hygieneartikel",
"Magische Kreaturen",
"Wagenräder",   ]},
{"title": "d10 Der Typ des Geschäftes ist...", "id":"d10theshopstypeis_shops", "roll":[
"Ein Gebäude in einem Kaufmannsviertel",
"An das Haus des Kaufmanns angeschlossen",
"Ein Wagen, gezogen von einem Pferde- oder Ochsengespann",
"Unter einem Zelt",
"In einem offenen Basar auf einem Teppich",
"In einem Stand auf einem Basar",
"Im Hinterzimmer eines anderen Ladens",
"Eine Händlerkarawane",
"An einem Ort der nur durch Magie zugänglich ist",
"Ein Franchise. Der Laden kann an mehreren Orten gefunden werden",]},
{"title": "d12 Der Laden gehört...", "id":"d12theshopisownedby_shops", "roll":[
"Einem scharfäugigen Buchhalter",
"Einem Gildenleiter",
"Einem Adligen",
"Einem zwanghaften Gnom",
"Einem gierigen Zwerg",
"Einem ehemaligen Soldaten",
"Der Frau eines Bauern",
"Einem hochnäsigen Hochelfen",
"Einem vergesslichen Halbling",
"Einer unterdrückten Brut",
"Einer alten Frau",
"Einem faulen Halb-Ork",]},
{"title": "d6 Der Zustand des Geschäfts ist...", "id":"d6theshopsconditionis_shops", "roll":[
"Brandneu. Alles hat einen Platz und ist an seinem Platz",
"Gut gepflegt. Es wird regelmäßig gereinigt",
"Durchschnittlich. Ein bisschen staubig",
"Ungepflegt. Ungeziefer und Nagetiere huschen weg von dir",
"Dunkel. Es gibt kein natürliches Licht. Nur eine oder zwei Kerzen erleuchten den Laden",
"Baufällig. Das Gebäude sollte abgerissen werden",]},
{"title": "d6 Der Zustand der Ware ist...", "id":"d6theconditionofthemerchandiseis_shops", "roll":[
"Makellos. Im besten Zustand gehalten",
"Regelmäßig gereinigt",
"Gemixt. Manche Gegenstände sehen neu aus, manche sehen so aus, als wären sie schon lange da",
"Staubig und dreckig",
"Auseinanderfallend",
"Antik",]},
{"title": "d6 Der Laden bezieht seine Vorräte von...", "id":"d6theshopgetsitssuppliesfrom_shops", "roll":[
"Sie werden vom Händler selbst hergestellt oder besorgt",
"Sie werden von den Lehrlingen des Kaufmanns hergestellt oder besorgt",
"Geschäftspartnern des Händlers",
"Sie werden anderswo in Masse gefertigt und im Laden verkauft",
"Sie werden von anderen Menschen in der Stadt gekauft und weiterverkauft",
"Niemand weiß es, und niemand fragt nach",]},
{"title": "d8 Die Preise der Preise sind...", "id":"d8theitemsarepriced_shops", "roll":[
"Ziemlic fair",
"Unter dem eigentlichen Wert",
"Über dem eigentlichen Wert",
"Exorbitant",
"Alles ist zum Tausch angeboten",
"Andere ´Zahlungsmittel´ werden gefördert ",
"Basierend auf der Stimmung des Händlers",
"Basierend darauf, wie stark der Händler denkt, dass der Kunde es braucht.",]},
{"title": "d5 Die Größe des Ladens ist...", "id":"d5theshopssizeis_shops", "roll":[
"Riesig. Mehrere Räume",
"Groß. Ein großes Zimmer",
"Durchschnittlich. Ein Zimmer groß genug, um zu beinhalten, was benötigt wird",
"Klein. Das Zimmer fühlt sich überladen an",
"Wintig. Der Händler verkauft praktisch aus einer Tasche",]},
{"title": "d4 Wie beschäftigt ist der Laden...", "id":"d4howbusyistheshop_shops", "roll":[
"Es ist einer der beliebtesten Orte, die man besuchen kann",
"Ein paar Leute schländern in den Laden ein und aus",
"Nicht sehr beschäftigt. Sie sind die einzigen Leute dort",
"Es sieht selten einen Kunden",]},
{"title": "d50 Etwas Interessantes, das sie herausfinden...", "id":"d50somethinginterestingyoufind_shops", "roll":[
"Der Ladenbesitzer wohnt in einem Raum, der mit dem Geschäft verbunden ist",
"Es gibt einen geheimen Raum in der Rückseite des Gebäudes, in dem illegale Waren verkauft werden",
"Der Ladenbesitzer scheint nicht dahin zu gehören",
"Einer der Gegenstände scheint nicht dahin zu gehören",
"Eine Glocke läutet jedes Mal, wenn jemand den Laden betritt",
"Der Ladenbesitzer ist ungewöhnlich freundlich",
"Der Ladenbesitzer scheint keine Geschäfte machen zu wollen",
"Manche Gegenstände sind seltsam magisch (oder nicht magisch)",
"Sie fühlen eine unsichtbare Präsenz, die Sie beobachtet",
"Magische Barrieren verhindern, dass Menschen mit Waren interagieren",
"Ein Goblin bearbeitet einige der Waren",
"Ein Oger ist an einer der Wände angeleint",
"Ein paar Hunde behalten ein Auge auf dich, während sie an einem Knochen kauen",
"Eine Katze folgt dir im Laden",
"Eine Ziege scheint Wache vor dem Laden zu halten",
"Ein Rattennest bildet sich in einer abgelegenen Ecke",
"Ein sprechender Vogel besteht darauf, dir Obszönitäten zuzurufen",
"Viele Sachen werden zum Verkauf verpackt",
"Eine neue Sendung ist gerade angekommen und wird ins Lager gebracht",
"Man hört Geräusche vom Dach oder vom Raum über dem Laden",
"Der Boden ist aufgebrochen",
"Der Händler räumt einen Gegenstand weg, der in der Werkstatt ruiniert wurde",
"Der Ladenbesitzer streitet sich mit einem Angestellten",
"Ein Affe folgt dir und versucht dir Waren zu geben",
"Fußabdrücke führen direkt in eine Wand",
"Ein Rabe versucht, Gegenstände aus deiner Tasche zu stehlen",
"Die kleinen Kinder des Kaufmanns versuchen erfolglos einen Verkauf abzuschließen",
"Der Händler spricht nicht",
"Dinge ändern sich, wenn man nicht hinsieht",
"Musik spielt im ganzen Laden",
"Der Händler kann von allen, was er verkauft, eine Geschichte erzählen",
"Einige der Gegenstände scheinen gestohlen",
"Der Laden ist nur nachts geöffnet",
"Der Laden ist für den Tag geschlossen",
"Ein ungewöhnliches Objekt steht zum Verkauf mit einer dunklen Hintergrundgeschichte",
"Ein paar Schläger halten den Händler auf",
"Einer der Kunden versucht zu klauen",
"Der Laden riecht stark nach Schimmel",
"Der Laden gehört einem Freund oder ehemaligen Parteimitglied",
"Ein Geist durchstöbert die Waren",
"Der Ladenbesitzer schläft",
"Der Ladenbesitzer hat einen stechenden und beleidigenden Geruch",
"Der Ladenbesitzer ist ein energischer Verkäufer",
"Eine legendäre Waffe ist ausgestellt, aber nicht zu verkaufen",
"Wandmalereien säumen die Wände",
"Der Kaufmann besteht darauf, dass er aus einer alten Linie mächtiger Kaufleute stammt",
"Der Händler kleidet sich viel besser als erwartet",
"Der Kaufmann sieht aus wie ein Bettler",
"Polizisten oder die örtliche Wache interviewen alle im Laden",
"Der Ladenbesitzer ist gerade gestorben",]},


{"title": "d8 Der Marktplatz befindet sich in...", "id":"d8themarketplaceislocatedin", "roll":[
"Einem breiten, rechteckigem Platz.",
"Einem großen, kreisförmigen oder elliptischen Platz.",
"Einem großen Platz mit einer polygonalen Form (d4): 1. perfektes Quadrat; 2. Trapez; 3. Dreieck; 4. Fünfeck.",
"Einer Kreuzung von zwei breiten Straßen.",
"Einem weitläufigen Labyrinth aus kleinen Gassen.",
"Einem weitläufigen Labyrinth von Tunneln unter den Straßen der Stadt.",
"Ein riesiger Pavillon mit einem festen Dach über dem Kopf.",
"Einer unorganisierten Reihe von großen Zelten.",]},
{"title": "d10 Verkaufsstände, Wagen und Stände werden meistens organisiert nach...", "id":"d10vendorstallscartsandboothsaremostlyorganizedby", "roll":[
"Art der Ware.",
"Herkunftsland der Ware.",
"Rasse oder Ethnizität der Kaufleute.",
"Nichts; der Ort ist eine große desorganisierte Chaos.",
"Religiöse oder politische Zugehörigkeit der Kaufleute",
"Rohstoffe und Industriegüter in der einen Hälfte des Marktes, Fertigprodukte in der anderen Hälfte.",
"Importierte Güter in einer Hälfte des Marktes, lokale Güter in der anderen Hälfte.",
"Einen komplizierten und archaischen System, das in einem uralten staatlichen oder religiösen Dokument niedergelegt ist.",
"Der soziale Klasse, auf die der Verkäufer abzielt.",
"Der Reihenfolge der Ankunft auf dem Marktplatz an jedem beliebigen Tag.",]},


{"title": "d50 Siedlungsname (1. Teil)...", "id":"d50settlementnamepart1", "roll":[
"Stein.",
"Wasser.",
"Blatt.",
"Eis.",
"Flamme.",
"Sonne.",
"Sturm.",
"Erde.",
"Glänzen.",
"Star.",
"Kunst.",
"Krieg.",
"Herz.",
"Hart.",
"Fallen.",
"Gestein.",
"Untergang.",
"Eiche.",
"Reißen.",
"Rabe.",
"Dachs.",
"Schlange.",
"Löwe.",
"Hölle.",
"Wut.",
"Seezunge.",
"Ratte.",
"Bock.",
"Lilie.",
"Ader.",
"Gestank.",
"Magier.",
"Gott.",
"Boden.",
"Rein.",
"Mal.",
"Nocken.",
"Morsch.",
"Klar.",
"Teilt.",
"Gründer.",
"Erbe.",
"Messe.",
"Dreh.",
"Lord's",
"König.",
"Dienerin.",
"Dämonen.",
"Schnee.",
"Land's.",]},
 {"title": "d50 Siedlungsname (2. Teil)...", "id":"d50settlementnamepart2", "roll":[
"kamm.",
"brücke.",
"lauf.",
"fang.",
"klinge.",
"oase.",
"erhebung.",
"rodung.",
"licht.",
"haupt.",
"flamme.",
"ort.",
"riss.",
"falz.",
"erholung.",
"gastgeber.",
"zunft.",
"höhle.",
"loch.",
"tal.",
"hammer.",
"pike.",
"schiene.",
"spitze.",
"ring.",
"henge.",
"spule.",
"frühling.",
"kiefer.",
"fleck.",
"hagel.",
"see.",
"kind.",
"feste.",
"fort.",
"bach.",
"weg",
"schmelze.",
"bezirk.",
"furt.",
"kraul.",
"moral.",
"kar.",
"tal.",
"garten.",
"wunsch.",
"gefährte.",
"grat.",
"station.",
"stadt.",   ]},
 {"title": "d6 Einwohnerzahl...", "id":"d6populationsize", "roll":[
"50 Leute (Weiler).",
"100 Menschen (kleines Dorf).",
"250 Menschen (Dorf).",
"1'000 Menschen (Kleinstadt).",
"5'000 Menschen (Stadt).",
"25'000 Menschen (Stadt).",]},
 {"title": "d100 Die Meisten der Einwohner sind...", "id":"d100maininhabitantsare", "roll":[
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Menschen",
"Waldelfen",
"Waldelfen",
"Waldelfen",
"Waldelfen",
"Waldelfen",
"Hochelfen",
"Hochelfen",
"Hochelfen",
"Hochelfen",
"Hochelfen",
"Hochelfen",
"Hochelfen",
"Hochelfen",
"Hochelfen",
"Eladrin",
"Eladrin",
"Halbelfen",
"Halbelfen",
"Drow",
"Drow",
"Bergzwerge",
"Bergzwerge",
"Bergzwerge",
"Bergzwerge",
"Bergzwerge",
"Bergzwerge",
"Bergzwerge",
"Bergzwerge",
"Bergzwerge",
"Bergzwerge",
"Hügelzwerge",
"Hügelzwerge",
"Hügelzwerge",
"Hügelzwerge",
"Hügelzwerge",
"Leichtfüßige Halblinge",
"Leichtfüßige Halblinge",
"Leichtfüßige Halblinge",
"Stout Halblinge",
"Stout Halblinge",
"Steinzwerge",
"Steinzwerge",
"Waldzwerge",
"Waldzwerge",
"Tiefengnome",
"Drachengeborener",
"Drachengeborener",
"Drachengeborener",
"Drachengeborener",
"Drachengeborener",
"Orks und Halborks",
"Orks und Halborks",
"Orks und Halborks",
"Tieflinge und Teufel",
"Tieflinge und Teufel",
"Aarakocra",
"Aarakocra",
"Genasi und Elementals",
"Genasi und Elementals",
"Gestaltwandler und Lykanthropen",
"Gestaltwandler und Lykanthropen",
"Goliaths und Riesen",
"Wechselbälger und Doppelgänger",
"Kriegsgeschmiedete und Konstrukte",
"Aasimar und Himmlische",]},
 {"title": "d20 Die Atmosphäre der Siedlung ist...", "id":"d20thesettlementsatmosphereis", "roll":[
"Ruhig.",
"Malerisch.",
"Friedlich.",
"Vage beunruhigend.",
"Entschieden unheimlich.",
"Angespannt.",
"Heftig.",
"Ängstlich.",
"Geschäftig.",
"Tumultig.",
"Chaotisch.",
"Angenehm.",
"Dunkel.",
"Schwer.",
"Erstickend.",
"Entspannend.",
"Befreiend.",
"Spirituell.",
"Apathisch.",
"Traurig.",]},
 {"title": "d100 Ein markantes Merkmal der Siedlung ist oder sind...", "id":"d100aprominentfeatureofthesettlementis", "roll":[
"Die schönen Parks.",
"Die majestätischen Obstgärten.",
"Eine bemerkenswerte Bibliothek.",
"Eine mächtige Gilde.",
"Der Geruch von gebackenem Brot.",
"Die Geräusche von arbeiteten Schmieden.",
"Die Fülle an Wild in der Umgebung.",
"Das weitläufige Ackerland, das es umgibt.",
"Die exotischen Waren.",
"Die Slums.",
"Das kriminelle Syndikat.",
"Die hochklassigen Bordelle.",
"Das Verbot der Prostitution.",
"Dass sie durch dicke Steinmauern geschützt ist.",
"Dass sie auf einem schwimmenden Erdteil steht.",
"Die sichtbaren magischen Schutzzauber, die Monster abstoßen.",
"Dass es ständig belagert wird.",
"Dass es von einem Tyrannen regiert wird.",
"Dass das Gesetz wird streng durchgesetzt.",
"Der Mangel an Regierung; Anarchie herrscht.",
"Ein großer Tempel.",
"Ein Friedhof, größer als es eigentlich gerechtfertigt ist.",
"Ein System von Tunneln unter der Siedlung.",
"Ein ebenes Tor.",
"Ein mächtiger Fluch.",
"Dass diese Abenteurer werden von den Menschen gehasst.",
"Ein geheimnisvoller Obelisk, der die anderen Gebäude überrägt.",
"Dass ein berühmter Entertainer bewohnt die Siedlung.",
"Das Magie von den Menschen gehasst wird.",
"Die schwer bewaffneten, gut ausgebildeten Wachen.",
"Das gezähmte Monster, das es verteidigt.",
"Eine gut genutzte Handelsroute, die durch sie verläuft.",
"Die freundlichen Bardamen.",
"Die lokale Ale Brennerei.",
"Eine Festung eines edlen Herrn.",
"Ein Turm, in dem eine Prinzessin eingesperrt ist.",
"Dass es von Schädlingen überrannt wird.",
"Dass es in einer wirtschaftlichen Depression ist.",
"Dass es von einem intelligenten Monster erpresst wird.",
"Eine Gruppe von Flüchtlingen, die in der Nähe der Siedlung zelten",
"Dass es auf dem Weg einer Zigeunerkarawane liegt.",
"Dass ein reisender Karneval oft durchzieht.",
"Die nahen Weinberge.",
"Ihre Geschichte als Schlachtfeld.",
"Ihre Nähe zu einer Monsterfestung.",
"Ein Wunschbrunnen mit einer lokalen Legende.",
"Dass es in einer Zone gebaut ist, in der Magie nicht funktioniert.",
"Dass es in einer wilden magischen Zone gebaut wird.",
"Dass es der Ort eines mythischen Ereignisses war.",
"Dass es auf antiken Ruinen erbaut wurde.",
"Eine Statue zu Ehren eines längst verstorbenen Helden.",
"Eine Fülle eines bestimmten Tieres.",
"Ein Schrein für einen bösen Gott.",
"Eine erschwingliche Zeitschrift, die Nachrichten des Reichs vermittelt.",
"Ein friedlicher Kult.",
"Ihre breiten Straßen.",
"Ihre unglaublich schöne Architektur.",
"Ihre Schirmherrschaft der Künste.",
"Die nahe gelegene Akademie der Magie.",
"Die seltenen Kräuter, die in der Nähe wachsen.",
"Die Verwendung von glühendem Kristall als Straßenlaternen.",
"Das Astronomie-Observatorium der Siedlung.",
"Eine Brücke, die einen breiten Fluss überspannt.",
"Die stark patriotischen Bewohner.",
"Ein Galgen, der auf dem Hauptplatz aufgestellt ist.",
"Ein genialer Geist.",
"Ihre Keine-Waffen-Politik.",
"Ein korrupter Politiker.",
"Regelmäßige Überfälle von einer Gruppe von Banditen in der Nähe.",
"Dass es von Kannibalen gegründet wurde, und einige setzen die Tradition fort.",
"Das es eigentlich eine Banditenbasis ist.",
"Dass alles Licht außer Sonnenlicht erlischt.",
"Das es der Ort ist, an dem der Schatz eines Piraten vergraben und noch nicht beansprucht wurde.",
"Die nahe gelegenen Minen.",
"Eine Geschichte von Attentaten.",
"Ihre sehr progressive Einstellung.",
"Ihre entschieden konservative Haltung.",
"Der inkompetenter Spitzbold eines Anführers.",
"Ihre Paranoia.",
"Ihre Fremdenfeindlichkeit.",
"Ihre Toleranz gegenüber anderen.",
"Der Hexenzirkel, der als Herrscher funktioniert.",
"Die überwiegend männliche Bevölkerung.",
"Die überwiegend weibliche Bevölkerung.",
"Die hohe Konzentration von Kindern.",
"Der spürbare Mangel an Kindern.",
"Ihre Verbindung zu den Feywild.",
"Ihre Verbindung zum Schattenfell.",
"Ein schmutziges Gefühl.",
"Der Gestank von Abwasser.",
"Der Fluss, der es teilt.",
"Die untoten Diener, die Arbeit verrichten.",
"Dass es das Zentrum einer Menschenjagd ist.",
"Ein Pony-Maskottchen mit einem liebenswerten Namen.",
"Der überwältigende Geruch von Schwefel.",
"Ein niedriges Brummen, das die Siedlung ohne bekannte Ursache durchdringt.",
"Der tausendjähriger Baum auf dem Stadtplatz.",
"Dass es unter dem Schutz freundlicher Elementargeister steht.",
"Die glühende Hitze seiner Schmieden.",
"Ihre berühmte Unparteilichkeit.",]},
 {"title": "d30 Die Spieler sollten sich für die Siedlung interessieren, weil...", "id":"d30theplayersshouldcareaboutthesettlementbecause", "roll":[
"Es einen Laden für magische Gegenstände hat.",
"Kürzlich ein Verlies in der Nähe entdeckt wurde.",
"Ein mächtiger Zauberer dort lebt.",
"Ein NPC, den die Spieler zuvor getroffen haben, da ist.",
"Etwas, das sie wollen, da ist.",
"Ein Dieb hat ihnen etwas gestohlen hat, und dorthin geflohen ist.",
"Sie in einem Brief erwähnt wurde, der bei einem erschlagenen Feind gefunden wurde.",
"Sie von jemandem in der Siedlung angeheuert wurden.",
"Dies die einzige Siedlung innerhalb von vielen Kilometern ist, die Nachschub anbietet.",
"Einer der Bewohner um Hilfe bei einem Problem bat.",
"Es der einzige sichere Hafen von der von Ungeheuern betroffenen Umgebung ist.",
"Sie in ein Verbrechen verwickelt sind und gebeten wurden, die Stadt nicht zu verlassen.",
"Es da einige interessante Gerüchte über ihre Feinde gibt.",
"Die Spieler einige Gefangene befreit haben, die darum gebeten haben, dorthin gebracht zu werden.",
"Ein Feind sie aufgefordert hat.",
"Die Belohnungen der Aufträge recht hoch sind.",
"Die Dinge da sich unnatürlich verhalten, vielleicht ist eine Untersuchung erforderlich.",
"Sie immer wieder erwähnt wird, wohin auch immer sie gehen.",
"Die Städter sie wie Helden begrüßen.",
"Sie sich vor einem schweren Sturm schützen müssen.",
"Sie Hilfe brauchen, die die Siedlung bieten kann.",
"Ein Kind / ein hilfloser NPC in Gefahr ist und Hilfe braucht.",
"Es Anzeichen eines Monsterbefalls.",
"Eine Kreatur, deren Ziele sich mit denen der Gruppe schneidet, dort lebt.",
"Ein mächtiger NPC versucht, die Siedlung mit Geas unter seine Kontrolle zu bringen.",
"Ein Patron ihnen dort Arbeit verspricht.",
"Sie Gerüchte von einem versteckten magischen Gegenstand in der Nähe hören.",
"Ein seltsames Verbrechen begangen wird, das sie peripherisch einbezieht.",
"Ein lokaler NPC ihnen einen Gefallen getan hat und nun selber einen Gefallen einfordern möchte.",
"Eine mächtige Entität ihnen dort einen Deal anbietet.",]},



{"title": "d10 Der Name des Geschäftes ist", "id":"d10thenameoftheshopis", "roll":[
"old Grindylocks",
"Verzauberungen und Flüche",
"Zappliger Sam",
"Banshees, Bassilisken und Betrachter",
"Hextech und andere magische Dinge",
"Die krabbelnde Klaue",
"Der zischende Feuerball",
"Die wilde magische Welle",
"Federn des Phönix",
"Michales magisches Zubehör",]},
{"title": "d20 Der Laden befindet sich", "id":"d20theshopislocated", "roll":[
"Unter Tage",
"In den Slums",
"Auf dem Markt",
"Im Wirtshauskeller",
"In dem Haus eines Zauberkundigen",
"An den Docks",
"Auf einem Schiff",
"Im gleichen Gebäude wie die Zauberer-Taverne",
"Im geheimnisvollen Bezirk",
"Auf dem Stadtplatz",
"In einer von Elfen bewohnten Gasse",
"in einer Gasse, die hauptsächlich von Zwergen bewohnt wird",
"In einer Gasse, die hauptsächlich von Gnomen bewohnt wird",
"in einer Gasse, die hauptsächlich von Tieflings bewohnt wird",
"in einer Gasse, die hauptsächlich von Goblins bewohnt wird",
"Im edlen Bezirk",
"Am Eingang des Colloseums",
"Im Wagen eines reisenden Kaufmanns",
"Auf einem Berg",
"Am Grund eines Flusses",]},
{"title": "d10 Der Laden verkauft", "id":"d10theshopsells", "roll":[
"Schmuckstücke und Accessoires, nichts von großer Kraft",
"Zaubertränke und Gifte",
"Liebestränke, Viagra und andere solche Dinge",
"Weissagungen",
"Materialkomponenten für verschiedene Zaubersprüche",
"Zauberbücher und magische Tinte",
"Magische Waffen",
"Magische Rüstung",
"Zauberschriftrollen",
"Verzauberte Tiere",]},
{"title": "d10 Der Laden gehört", "id":"d10theshopisownedby", "roll":[
"Einem unglaublich alten Menschen",
"Einem, herumrennenden Gnom",
"Einem vergesslichen Halbling",
"Einem gierigen und bösartigen Goblin",
"Einem Schurkenzauberer",
"Einer Fee",
"Einem hochnäsigen Hochelf",
"Einem Zauberer, der ständig experimentiert",
"Einem Ifriti der versuchtt, ein Abkommen für deine Seele zu treffen",
"Einem Krieger, der nichts von Magie versteht, sondern die Güter verkauft, die er im Laufe der Jahre gefunden hat",]},
{"title": "d10 Der Ort ist", "id":"d10theplacelooks", "roll":[
"Verdächtig",
"Unberührt",
"Natürlich",
"Abgenutzt",
"Am Leben",
"Unglaublich klein von innen, verglichen mit dem, wie es auf der Außenseite aussieht",
"Unglaublich groß von innen verglichen mit dem, wie es auf der Außenseite aussieht",
"Verkohlt",
"Erfroren",
"Glänzend",]},
{"title": "d10 Ein Merkmal der hier verkauften Artikel ist, dass", "id":"d10acharacteristicoftheitemssoldhereis", "roll":[
"Sie alle in schlechter Verfassung sind",
"Sie unbekannte Auswirkungen haben",
"Sie instabil  sind und beim Gebrauch magische Energie freisetzen",
"Sie abgelaufen sind (zum Beispiel ein abgelaufener Zauber)",
"Sie verflucht sind",
"Sie gesegnet sind",
"Die Gegenstände alle gestohlen sind",
"Die Gegenstände eine großartige Geschichte haben",
"Der ehemalige Besitzer noch nach ihnen sucht",
"Die Gegenstände uralt sind",]},

{"title": "d8 Die Arena ist...", "id":"d8thearenais", "roll":[
"Eine uralte Steinstruktur, benutzt seit Jahrhunderten.",
"Eine alte Steinstruktur, benutzt seit Generationen.",
"Eine wundersame Konstruktion mit großen Tribünen, Falltüren und Aufzügen.",
"Eine robuste Holzkonstruktion, vor kurzem gebaut.",
"Eine brandneue Steinstruktur, kürzlich gebaut.",
"Eine Reihe wackeliger Holzständer um einen Dreckring.",
"Ein Seilkreis umgeben von Zuschauern und ein paar Käfigen.",
"Eine unterirdische Grube mit Zuschauern, die sich über ein Geländer beugen.",
]},
{"title": "d8 Die Spiele werden abgehalten...", "id":"d8thegamesarebeingheld", "roll":[
"Zu Ehren des Geburtstages des Souveräns.",
"Zu Ehren eines historischen Jubiläums.",
"Zu Ehren eines kürzlichen militärischen Sieges.",
"Um einen legitimen Gewinn für die Organisatoren zu erzielen.",
"Um einen Gewinn für die Organisatoren zu machen.",
"Um Gefangene zu entsorgen",
"Um die Massen zu unterhalten.",
"Um einen Champion für eine gefährliche Aufgabe oder traditionelle Zeremonie zu bestimmen.",
]},
{"title": "d8 Das Hauptereignis ist...", "id":"d8themaineventis", "roll":[
"Ein Battle-Royale oder Großkampf.",
"Eine Nachstellung eines historischen Kampfes.",
"Ein Duell zwischen zwei Arena-Champions.",
"Ein Duell zwischen einem Champion und einem unterlegenen Außenseiter.",
"Die Verfütterung von Gefangenen an Bestien",
"Eine Schlacht von Mensch gegen Tier (d8): 1. Bären; 2. Chimären; 3. Drachen; 4. Riesenspinnen; 5. Löwen; 6. Eulenbären; 7. Tiger; 8. Wölfe.",
"Ein Wagenrennen oder ein Rennen zu Fuß.",
"Heldentaten.",
]},
{"title": "d12 Der Sieger des Tages gewinnt...", "id":"d12thedayschampionwins", "roll":[
"Eine schwere Börse aus Silber.",
"Ein beträchtlicher Geldbeutel mit Gold.",
"Eine teure und verzierte Waffe.",
"Ein teures und verziertes Stück Rüstung.",
"Eine Blumenkrone und eine feine Silberkette.",
"Eine Blumenkrone und ein juwelenbesetzter Goldgürtel.",
"Ein feiner Seidenumhang und eine juwelenbesetzte Silberkette.",
"Eine Petition des Souveräns.",
"Eine Ehrenposition in der Armee und einen Geldbeutel mit Silber.",
"Eine Ehrenposition in der Garde des Souveräns.",
"Eine Woche Verwöhnung und Vergnügen und eine Börse mit Silber.",
"Eine Nacht mit einer der Frauen des Adels und einen Geldbeutel mit Gold.",
]},
{"title": "d6 Die Einstellung der Menge ist...", "id":"d6thecrowdsattitudeis", "roll":[
"Laut und festlich.",
"Eifrig und aufgeregt.",
"Entspannt und gelassen.",
"Feindlich und angespannt.",
"Enttäuscht und wütend.",
"Rauflustig und rebellisch.",
]},
{"title": "d8 Die Menge besteht hauptsächlich aus...", "id":"d8thecrowdismadeupofmostly", "roll":[
"Kaufleuten, Adligen und Wohlhabende.",
"Soldaten, Offiziere und Lagerfolger.",
"Lokalen Handwerkern und Ladenbesitzern.",
"Lokalne Bauern und ungelernte Arbeitern.",
"Ausländern und Reisenden.",
"Sklaven, Diener und Arbeitern.",
"Matrosen, Piraten und Schurken.",
"Menschen aller sozialen Schichten.",
]},
{"title": "d200 Dieser Ort heißt...", "id":"d200thisplaceiscalled", "roll":[
"Daisies.",
"The Don.",
"Blinkers.",
"The Prude's Suspenders.",
"Gold’s Dust.",
"The Velvet Fang.",
"The Whisper Home.",
"The Hook.",
"Over the River.",
"Slooshes.",
"The Rapid Rascal.",
"The Stoat.",
"The Fidgety Ferret.",
"Long Shaft.",
"The Guards.",
"Chastity’s.",
"The Mask.",
"The Red Dress.",
"Jewels.",
"Silken Flute.",
"The Nag’s Head.",
"Drummers.",
"Sailors Choice.",
"Blacksmiths Envy.",
"The Nagging Wife.",
"Colins Rubble.",
"Dron's Beat.",
"The Wink.",
"Maggie’s Horn.",
"The Sun & Cider.",
"The Oakworm.",
"Tickle & Feather.",
"The Mistress.",
"Madam Zersannies's.",
"The King's Court.",
"The Cursed Coin.",
"Slit.",
"The Maiden Head.",
"The Rusty.",
"The Silken Ferret.",
"Long Legs.",
"Elven Whispers.",
"The Leg.",
"False Suspenders.",
"Aunt Fannies Bloomers.",
"Final Rest.",
"Cocks Crow.",
"The Unblinking Eye.",
"The Bountiful Bosom.",
"Tuskers.",
"The Thrusting Gentleman.",
"Tally Hoes.",
"Rutting.",
"Pigs in Blankets.",
"The Delicate Touch.",
"Aphrodite’s Wish.",
"The Dirty Secret.",
"Long Locks.",
"Sweat.",
"Brothel.",
"Taters.",
"The Swift Finish.",
"Cumberlands.",
"The Missing Sausage.",
"The Fools Frolic.",
"Dragons.",
"The Bushel.",
"Farmers Oats.",
"The Raised Brow.",
"Genies.",
"The Farfetched Feather.",
"Junk.",
"The Connoisseur’s Choice.",
"Colossus.",
"The Smooth Ride.",
"Bucking.",
"The Great Big Globes.",
"The Glimmeric.",
"Loving Embrace.",
"Chokers Necklace.",
"The Grand Madame's Emporium of Fine Delicacies, Treats, and the Exotic.",
"Thug’s Retreat.",
"Warriors' Return.",
"Gold Gobblers.",
"Cackling Croons.",
"The Warty.",
"Bessie’s Best.",
"Corset.",
"Winkies.",
"The Shagger.",
"Port of Call.",
"The Home Away from Hoes.",
"Smooth.",
"The Maiden Fair.",
"The Bit.",
"Hosted.",
"Glamourous Delights",
"Happily Ever After.",
"Sultry Stare.",
"The Full Flush.",
"The Lighted Candle.",
"The Red Candle.",
"The Raised Candle.",
"The Dancing Flame.",
"The Candlelight Resort.",
"The Sweetest Cherry.",
"Cherry's.",
"Cherry Pie.",
"The Velvet Cherry.",
"The Golden Cherry.",
"The Silk Curtain.",
"The Red Curtain.",
"The Lacy Curtain.",
"The Welcoming Curtain.",
"The Satin Curtain.",
"Satin Dolls.",
"Sweet Dolls.",
"Porcelain Dolls.",
"The Sugar Doll.",
"Dancers and Dolls.",
"The Red Door.",
"The Golden Door.",
"The Silver Door.",
"The Maiden's Door.",
"The Dancers' Door.",
"Lover's Embrace.",
"Lady's Embrace.",
"The Sweetest Embrace.",
"The Warmest Embrace.",
"Welcoming Embrace.",
"The Satin Glove.",
"Silky Gloves.",
"Lacy Gloves.",
"The Lady's Glove.",
"The Maiden's Glove.",
"The Shining Heart.",
"Pink Hearts.",
"Lacy Hearts.",
"Sweetheart's",
"The Maiden's Heart.",
"The Night House.",
"The Pink House.",
"The Porcelain House.",
"The Welcoming House.",
"The Cozy House.",
"The Warmest Lamp.",
"The Red Lamp.",
"The Pink Lamp.",
"The Soft Lamp.",
"The Lady's Lamp.",
"The Lady's Kiss.",
"The Maiden's Kiss.",
"The Night's Kiss.",
"Cozy Kisses.",
"Satin Kisses.",
"Peach's Place.",
"The Peach.",
"The Prettiest Peach.",
"The Sweetest Peach.",
"The Golden Peach.",
"The Silky Purse.",
"The Satin Purse.",
"The Lady's Purse.",
"The Dancer's Purse.",
"The Pink Purse.",
"The Maiden's Room.",
"The Lovers' Room.",
"The Night Room.",
"The Warm Room.",
"The Red Room.",
"The Silver Slipper.",
"The Satin Slipper.",
"The Silk Slipper.",
"The Red Slipper.",
"The Dancer's Slipper.",
"The Lacy Skirt.",
"The Welcoming Skirt.",
"The Pink Skirt.",
"The Dancer's Skirt.",
"The Lady's Skirt.",
"The Maiden's Shoe.",
"The Red Shoe.",
"Cozy Shoes.",
"Lovers' Shoes.",
"Silver Shoes.",
"Silky Stockings.",
"The Red Stocking.",
"The Lacy Stocking.",
"The Lady's Stocking.",
"The Softest Stockings.",
"The Maiden's Veil.",
"The Lacy Veil.",
"The Silk Veil.",
"The Lovers' Veil.",
"The Veil of Night.",
"Soft-Lighted Window.",
"The Shining Window.",
"The Lighted Window.",
"The Pink Window.",
"The Welcoming Window.",
]},
{"title": "d20 Das Bordell befindet sich...", "id":"d20thebrothelislocated", "roll":[
"In den Slums.",
"In einer Barackenstadt.",
"In einer wohlhabenden Wohngegend.",
"Im Hafenviertel.",
"In der Flussufergegend.",
"Im Kasernenviertel.",
"In einer Alle eines fremden Basars.",
"In einer Alle abseits des Marktplatzes.",
"Im Schatten eines Tempels.",
"Über einer wilden Taverne.",
"Hinter einer Taverne voller Krimineller.",
"Angrenzend an eine Taverne voller Spieler.",
"Unter Tage.",
"Außerhalb der Mauern der Stadt oder am Rande einer Stadt.",
"Am Fuß eines Zauberturms.",
"In der Höhle, in der einst ein Monster war.",
"Über einem Gasthaus an einer belebten Handelsroute.",
"Im Keller einer Taverne.",
"Auf einer Straße mit vielen anderen Bordellen.",
"In einem Haus in einem Park, Garten oder Wald.",
]},
{"title": "d10 Neben dem üblichen Bordell-Alltag, können Sie im Bordell folgendes kaufen: ...", "id":"d10inadditiontotheusualeverydaybrothelfarehereyoucanprocure", "roll":[
"Wirklich komische Sachen, für diejenigen mit den interessantesten Fetischen.",
"Illegales Zeug. Wenn das herausgefunden wird, wird der Ort niedergebrannt und die Besitzer gehängen. Es ist offensichtlich, dass es ein großes Geheimnis ist.",
"Darbietungen, die Essen beinhalten.",
"Ein Ventil, um gewalttätige Fantasien auszuleben.",
"Exotische Rassen.",
"Die schönsten Frauen und Männer. Nicht nur eine Behauptung, es ist die ehrliche Wahrheit, bezeugt von den Göttern.",
"Ein All-Inclusive-Pauschalangebot - alle Huren, Essen und Trinken, dass du verkraften kannst!",
"Bewusstseinsverändernden Drogen.",
"Zeug mit exotischen / magischen Zutaten, Tränken, etc.",
"Magische Freuden.",
]},
{"title": "d8 Der Ort wird geführt von...", "id":"d8theplaceisrunby", "roll":[
"Einem Kollektiv der Bewohner selbst.",
"Einer gemeinen alten Frau.",
"Einer großen gnädigen Frau mit einer ernsten Haltung.",
"Einer warmen mütterlichen Figur.",
"Einem mürrischen Tier.",
"Einem tyrannischen und grausamen Menschen.",
"Einer heißblütigen Verführerin.",
"Einer bezaubernden Hexe.",
]},
{"title": "d12 Zum Essen bietet der Ort an...", "id":"d12toeattheplaceserves", "roll":[
"Einfache Snacks.",
"Bankette.",
"Bauernessen.",
"Essen, man wird von einer Hure mit der Hand gefüttert.",
"Exotische Freuden.",
"Würzige Leckereien.",
"Einfaches Essen.",
"Süßigkeiten und Delikatessen.",
"Schmuddelige, schlecht gemachte Mahlzeiten.",
"Unbegrenzte Massen an Essen.",
"Einfacher Eintopf und Brot.",
"Nichts; es befriedigt andere Begierden.",
]},
{"title": "d8 Zum Trinken bietet der Ort an...", "id":"d8todrinktheplaceserves", "roll":[
"Ales.",
"Cocktails",
"Grog, und nichts als Grog.",
"Günstige Weine.",
"Met.",
"Die besten Weine und Champagner.",
"Lagervier.",
"Nichts; Rausch wird nicht toleriert.",
]},
{"title": "d10 Leute sprechen über diesen Ort; man sagt...", "id":"d10peopletalkaboutthisplacetheysay", "roll":[
"Die Mädchen sind unterbezahlt und schlecht behandelt.",
"Nichts wirklich; es ist ein Nachbarschaftsbordell.",
"Ein prominenter Adliger oder Kaufmann ist ein Stammkunde.",
"Die Göttin der Liebe und der Fruchtbarkeit segnete diesen Ort und alle ihre Anhänger müssen ihn besuchen.",
"Das übliche Zeug; ein neues Mädchen macht Aufsehen.",
"Einmal im Monat bietet es ermäßigte Dienstleistungen an.",
"Es ist heimlich die Heimat eines dunklen Kultes.",
"Alle Arbeiter dort sind verwandt.",
"Nicht viel, ein beliebtes Mädchen ist mit einem Kind schwanger.",
"Sie können für Dienstleistungen mit anderen Dingen als Münzen bezahlen (d6): 1. Vertragsarbeit, 2. Waren, 3. religiöse Dienstleistungen, 4. hochkarätige Einladungen, 5. Geheimnisse, 6. Lagerbier.",
]},
{"title": "d10 Leute sprechen über diesen Ort; Gerüchte deuten darauf hin, dass...", "id":"d10peopletalkaboutthisplacerumorssuggestthatrecently", "roll":[
"Ein Adliger eines der Mädchen geschwängert hat, weigert sich aber, sie oder das Baby anzuerkennen.",
"Jemand in der Nacht die Hälfte der Arbeiter und Kunden abgeschlachtet hat.",
"Ein Kunde mit einem Brieföffner erstochen wurde.",
"Ein Mann, der behauptete, ein Vorbild des Gottes der Liebe zu sein, den Ort besuchte.",
"Eine Gruppe empörter Bürger außerhalb des Bordells protestiert, angewidert von dem, was sie tun.",
"Der älteste Patron, der die letzten fünfzig Jahre jeden Tag das Bordell besucht hat, gestorben ist. Ein Tag der Trauer und des Feierns, zusammen mit einem üppigen Begräbnis, wird für ihn abgehalten.",
"Einer der Mitarbeiter erwürgt wurde.",
"Einer der Mitarbeiter sich in einen Klienten verliebt hat, aber er oder sie ist verheiratet.",
"Ein Loch im Keller aufgetaucht ist. Niemand kann den Boden sehen, und der Chef macht sich Sorgen, dass es wachsen und mehr Schaden anrichten könnte.",
"Mehrere Kunden sich mit einer Krankheit infiziert haben.",
]},
{"title": "d10 Zimmerausstattung: Dieses Zimmer hat...", "id":"d10roomfurnishingsthisroomhas", "roll":[
"Ein Himmelbett mit Samtvorhängen.",
"Ein Himmelbett mit Spitzenvorhängen.",
"Eine weiches Leder-Chaiselongue.",
"Eine Plüschrosa Chaiselongue.",
"Einen großen Stapel Kissen mit weichen Quasten.",
"Eienn großen Haufen Kissen mit Rüschenrändern.",
"Einen Tisch mit Obst und Wein darauf.",
"Einen Tisch mit Parfums und Ölen darauf.",
"Einen großen Spiegel an einer Wand.",
"Einen großen Spiegel an der Decke über dem Bett.",
]},
{"title": "d20 Features: Du bemerkst...", "id":"brotheld20featuresyounotice", "roll":[
"Den Duft von Lavendel.",
"Den Duft von  Flieder-Parfüm.",
"Den Duft von Ingwer und Zimt.",
"Den Duft von Rosen.",
"Duftkerzen.",
"Das sanfte rote Leuchten einer schattierten Lampe.",
"Eine Lampe, die schwach brennt.",
"Eine Statue von zwei küssenden Figuren.",
"Eine Statue von zwei Figuren, die sich verbinden.",
"Eine Statue einer nackten Frau beim Baden.",
"Ein Gemälde von mehreren Frauen beim Baden.",
"Ein Gemälde von einem Liebespaar.",
"Einen Vorhang aus Perlen.",
"Einen seidigen Vorhang.",
"Einen Plüschteppich unter deinen Füßen.",
"Eienn dicknr Pelzteppich unter deinen Füßen.",
"Den Klang von entfernter, sanfter Musik.",
"Den Klang von knarrenden Möbeln in der Nähe.",
"Einen langen, schrillen Schrei.",
"Ein langes Stöhnen.",
]},
{"title": "d20 Landmarke: Du siehst ein/eine/einen...", "id":"d20landmarkyouseeaan", "roll":[
"Akademie oder Universität.",
"Alte Ruine.",
"Arena.",
"Friedhof.",
"Bürgerhalle, Ratshalle oder Gildenhalle.",
"Anger oder Grünweg.",
"Festung.",
"Tor oder Bogen.",
"Bibliothek.",
"Leuchtturm oder Wachturm.",
"Marktplatz.",
"Denkmal (d4): 1. Mausoleum; 2. reflektierendes Becken; 3. große Statue; 4. botanischer Garten.",
"Monument (d6): 1. Koloss; 2. Säule; 3. Obelisk; 4. Plakette; 5. Statuengarten; 6. Wand.",
"Palast.",
"Paradegelände oder Übungsplatz.",
"Pier, Yachthafen oder reisenden Basar.",
"Plaza oder öffentlichen Platz.",
"Tempel.",
"Theater.",
"Viehhöfe.",
]},
{"title": "d20 Dieser Teil der Stadt ist/sind die/das...", "id":"d20thispartofthecityisthe", "roll":[
"Slums.",
"Wohnviertel, Unterschicht.",
"Wohnviertel, Mittelklasse.",
"Wohnviertel, Oberschicht.",
"Palastbezirk.",
"Tempelviertel.",
"Handwerksviertel.",
"Docks.",
"Flussuferviertel.",
"Hafenviertel.",
"Universitätsviertel.",
"Militärbezirk.",
"Marktviertel.",
"Gartenviertel.",
"Denkmalbezirk.",
"Nekropole.",
"Theaterviertel.",
"Bürgerliche Zentrum.",
"Ethnische Enklave.",
"Ausländische Enklave.",
]},
{"title": "d20 Die Einheimischen nennen diese Straße...", "id":"d20thelocalscallthisstreet", "roll":[
"(d8): 1. Armory Street; 2. Barricade Street; 3. Knight Street; 4. Moat Street; 5. Pike Street; 6. Rampart Street; 7. Shield Street; 8. Spear Street.",
"(d6): 1. Arch Street; 2. Bridge Street; 3. Canal Street; 4. Cross Street; 5. Pole Street; 6. River Street.",
"(d6): 1. Castle Street; 2. House Street; 3. Keep Street; 4. Manor Street; 5. Rock Way; 6. Tower Street.",
"(d8): 1. Cattle Road; 2. Common Street; 3. Green Street; 4. Greenway Street; 5. Meadow Lane; 6. Orchard Street; 7. Pasture Road; 8. Wildflower Lane.",
"(d12): 1. Anvil Street; 2. Cooper Street; 3. Forge Street; 4. Hammer Street; 5. Horseshoe Street; 6. Iron Street; 7. Mason Street; 8. Steel Street. 9. Tailor Street; 10. Stone Street; 11. Wright Street; 12. Weaver Street.",
"(d8): 1. Bluff Street; 2. Cliff Street; 3. Crestline Way; 4. High Street; 5. Highland Way; 6. Hill Street; 7. Hilltop Lane; 8. Ridge Street; 9. Ridgeline Way; 10. Summit Street.",
"(d8): 1. Devil's Alley; 2. Devil's Lane; 3. Low Street; 4. Magpie Lane; 5. Paupers Street; 6. Penny Lane; 7. Rat's Alley; 8. Serpent's Alley.",
"Market Street.",
"(d8): 1. Baker Street; 2. Hook Street; 3. Farm Road; 4. Feather Street; 5. Mill Street; 6. Pork Road; 7. Ranchers Road; 8. Stockyard Street.",
"(d8): 1. Banner Road; 2. Captains Street; 3. Drum Street; 4. March Street; 5. Parade Street; 6. Triumphant Way; 7. Trumpet Street; 8. Victory Lane.",
"(d6): 1. King Street; 2. Lords Lane; 3. Monarch Street; 4. Palace Way; 5. Queens Street; 6. Royal Street.",
"(d6): 1. Circle Street; 2. Borderline Road; 3. Curtain Street; 4. Townline Road; 5. Watch Street; 6. Wall Street.",
"(d8): 1. Bay Street; 2. Commerce Street; 3. Dockside Way; 4. Harbor Street; 5. Lake Street; 6. Pier Street; 7. Portside Way; 8. Water Street.",
"(d8): 1. Bayview Street; 2. Castleview Street; 3. Gardenview Street; 4. Greenview Street; 5. Harborview Street; 6. Marketview Street; 7. Riverview Street; 8. Waterview Street.",
"(d8): 1. North Road; 2. North Street; 3. South Road; 4. South Street; 5. East Road; 6. East Street; 7. West Road; 8. West Street.",
"(d12): 1. Beech Street; 2. Cedar Street; 3. Cherry Street; 4. Cypress Street; 5. Fir Street; 6. Maple Street; 7. Oak Street; 8. Palm Street; 9. Pine Street; 10. Spruce Street; 11. Walnut Street; 12. Willow Street.",
"(d8): 1. Northgate Street; 2. Southgate Street; 3. Eastgate Street; 4. Westgate Street; 5. Old Gate Road; 6. Rivergate Street; 7. Watchtower Street; 8. Watergate Street.",
"(d12): 1. Briar Street; 2. Bush Street; 3. Gardenia Lane; 4. Garden Street; 5. Lilac Street; 6. Lily Way; 7. Petal Street; 8. Poppy Street; 9. Rose Street; 10. Sunflower Lane; 11. Thorny Lane; 12. Violet Street.",
"(d6): 1. Emerald Way; 2. Jewelers Lane; 3. Golden Lane; 4. Rich Way; 5. Ruby Road; 6. Silver Lane.",
"(d8): 1. Bath Street; 2. Fountain Street; 3. Old Brick Road; 4. Old Stone Road; 5. Missing Street; 6. Stone Ruin Road; 7. Tumblestone Way; 8. Well Street.",
]},
{"title": "d20 Spiele, Wettbewerbe und Ereignisse", "id":"d20gamescontestsandevents", "roll":[
"Eine Gruppe von Bürgerlichen spielt Hufeisenwerfen.",
"Die Gruppe ist überrascht, als sie die Country Dart League in vollem Gange erleben. Die Kellnerinnen sind an das Chaos gewöhnt und weichen leicht aus. Der Halb-Oger-Türsteher benutzt Lawn Darts.",
"Eine Gruppe von Hügelzwergen ist in der Mitte eines Trinkwettbewerbs, und zwei von ihnen sind schon ohnmächtig. Der Preis ist ein fester Platin-Stein.",
"Nasses Kettenhemdwettbewerb!",
"Vier große Barbaren rufen lautstark während eines Armdrücken-Wettkampfs.",
"Eine schüchterne Teenagerin rezitiert schlechte Poesie in einer Ecke. Niemand schenkt ihr die geringste Aufmerksamkeit.",
"Es ist Trivialnacht! Diese Gelehrten von der Schule für Geschichte und Künste an der Universität gewinnen immer, aber heute Abend werden wir von der Schule der Alchemie diesen selbstgefälligen Buch-Snobs zeigen, was es heißt, ein Nerd zu sein.",
"Ein Promoter arbeitet sich an den Tischen herum und sucht nach Herausforderern, die gegen den lokalen Champion-Faustkämpfer kämpfen.",
"Es ist Wurstfest! Der Ort ist voller Zwerge, die das All-You-Can-Eat-Würstchen-Special verschlingen wollen.",
"Ein übergroßes Tier ist am Armdrücken, das die Hand aller in Sichtweite zerquetscht.",
"Einige Goblins rollen Würfel mit einigen animierten Skeletten an einem Tisch in der Ecke.",
"Ein Goblin macht den Anschein, dass er bei einem Würfelspiel schlecht betrügt, während ein Skelett beim Betrug eine hervorragende Arbeit leistet.",
"Ein 7'2 Fuß großer roter Drachengeborener mit einem 5 Fuß Bastardschwert hat einen Trinkwettbewerb mit einem Zwerg. Der Drachengeborene hat einen 4-Pint-Bierkrug und schafft es fast, Schritt zu halten. ",
"Eine Gruppe sitzt in der Ecke und spielt Karten. Alle betrügen, außer dem Paladin, der merkwürdigerweise immer gewinnt.",
"Ein Berg eines Mannes in Barbarenleder spielt Armdrücken mit einem kleinen Drachengeborenen und ist am Gewinnen.",
"Ein erweckter Seiler gewinnt zwei Billardspiele gleichzeitig.",
"Eine Gruppe betrunkener Wichtel spielt Verstecken, indem sie sich hinter Gönnern verstecken.",
"Die Spieler sind in eine regionale Kartenmeisterschaft gestoßen, die an diesem Abend ausgetragen wird. Der Buy-In ist riesig, aber auch der Pot.",
"Ein düster aussehender gnomischer Erfinder zeigt stolz seine neueste Erfindung. Er nennt es einen Spielautomaten ",
"Ein grauhaariger Geschichtenerzähler sitzt in der Nähe des Feuers und hält einen Wettbewerb ab. Er wird einen großen Geldbeutel für eine Geschichte geben, die er noch nicht gehört hat, aber bisher hat noch niemand gewonnen.",
]},
{"title": "d12 Unterhaltung", "id":"d12entertainment", "roll":[
"Der Barkeeper erzählt ausgeklügelte Geschichten darüber, woher der ausgestopfte Drachen auf dem Kaminsims kommt. In Wirklichkeit ist er ein pensionierter Zauberer und es ist sein Vertrautes, das krank wurde und starb. Er behält es als Andenken.",
"Ein Barde erzählt eine Geschichte über den letzten Akt des Wagnisses drs Spieler. Er verschönert ziemlich viel. Wenn er die Gruppe erkennt, macht er ein großes Spektakel.",
"Ein Barde erzählt die Geschichte des letzten Missgeschicks des Spielers. Es ist offensichtlicher Rufmord.",
"Eine lokale Bardengruppe, The Rolling Boulders, treten auf, und eine große Menge von betrunkenen Groupies hört nicht auf zu schreien.",
"Ein Bettler bietet an, für ein paar Kupfer zu singen. Sie haben ihn bis zum letzten Tisch singen gehört. Er ist schrecklich.",
"Eine freche Wahrsagerin hat sich in einem Eckstand niedergelassen. Sie informiert dich, dass du in naher Zukunft einen Kater sehen wirst.",
"Eine mitreißende Interpretation von The Lady and the Faerie Dragon lässt die Menge nach einer Zugabe von den Minnesängern rufen.",
"Der Lautenspieler fängt Unterwäsche von der Menge und legt sie über den lächerlichen gehörnten Helm, den er trägt.",
"Heute Nacht auf der Bühne: The Deep Tones. Ein Quartett von Zwergen mit langen Bärten und tiefen Stimmen, die a capella-Favoriten aus Orten ohne Licht (oder richtiger Musik) singen.",
"Heute Abend auf der Bühne: Shaela Windspeaker. Eine Elfen-Maid-Singerin-Liedschreiberin mit einer etwas weinerlichen Stimme, die sich langsam durch ihr jüngstes Protestlied gegen die vergessenen und vergangenen Jahrhunderte des Krieges bewegt.",
"Ein nervöser Show-Zauberer auf der kleinen Bühne macht Tricks mit Prestidigitation für die unamüsierten Gäste.",
"Es gibt ein Paar Musiker, die bekannte Trinklieder trällern. Sie haben eine improvisierte Bühne aus mehreren Tischen gemacht. Einer von ihnen scheint kurz vor dem Umfallen zu sein.",
]},
{"title": "d20 Gönner und Mitarbeiter", "id":"d20patronsandstaff", "roll":[
"Ein armer Landwirt versucht, seine Rechnung mit einem Sack Kartoffeln und einem Fass Gurken zu bezahlen.",
"Ein Seekapitän hat sich an einen Tisch gesetzt und versucht, Erinnerungsstücke und Souvenirs von seiner letzten großen Entdeckungsreise zu verkaufen. Vögel, exotische Münzen, winzige Meerjungfrauen, er hat alles. Einiges sieht jedoch falsch aus. Ein kleines bisschen sieht beunruhigend echt aus. ",
"Ein Ranger sitzt alleine in einer Ecke und raucht. Eine Kapuze bedeckt den größten Teil seines Gesichts. Zu seinen Füßen liegt ein schlafender Wolfshund. Jeder macht einen großen Bogen um ihn.",
"Ein einzelner Troll trinkt am Ende der Bar und weint leise und singt eine Country-Ballade nach der anderen.",
"Ein bekiffter Magier fummelt sich durch einen schrecklichen Kartentrick nach dem anderen.",
"Eine gemischte Gruppe von Elben trinkt schlechten Wein und hält duftende Taschentücher an die Nase, um den Gestank fernzuhalten. Einer hat einen Obsidianbogen um den Rücken geschnallt.",
"Eine junge Frau und ein ruppiger Mann stellen den Gönnern Fragen über sich selbst. Wenn sie zu den Spielern kommen, interessiert sich die Frau für ihre abenteuerlichen Geschichten. Sie wissen nicht, dass sie mit der Thronfolgerin und ihrer vertrauten Wache sprechen." ,
"Zwei Wächter streiten sich an einem Tisch darüber, wer der Kapitän mehr mag, indem sie fast identische Speere vergleichen und behaupten, den besseren zu haben.",
"Ein trauriger Clown trinkt allein ein Bier.",
"Eine hübsche junge Frau hält Gericht unter einigen ihrer Möchtegern-Verehrer. Ihr Vater unterbricht sie, und sie geht peinlich davon.",
"Irgendein Idiot hat einen Junggesellenabschied. Seine Freunde sind laut und beleidigen die Bardamen.",
"Es ist Ladies Night! Und es ist nicht enttäuschend ... Ein paar hübsche kleine Dinger von der Weberzunft sind hier, ein paar attraktive Heiler aus dem Tempel und die schöne neue Stadtbibliothekarin.",
"Eine mürrische alte Hexe trinkt Sherry und streichelt die fette graue Katze, die auf ihrem Schoß sitzt.",
"Der Barkeeper ist ein Marilith und vermischte vier Getränke gleichzeitig.",
"Die Bardame ist ein Sukkubus, sie gibt tolle Tipps.",
"Der Bademeister ist ein übel riechender Zombie. Er bietet dir eine Droge an.",
"Hinter der Bar ist ein gnomischer Alchemist mit einem Faible für Mixologie-Experimente.",
"Die zahnlose Putzfrau unterhält sich mit einem ehemaligen Hobgoblin-Militärist bei einem Ale darüber, wie ein Otyugh im Klo zu haben besser ist, als einen  Aaskriecher darin zu haben.",
"Die Bardame ist eine Doppelgängerin. Wenn sie mit deinen Getränken an deinen Tisch zurückkehrt, hat sie die Form eines deiner Gruppenmitglieder angenommen.",
"Ein dicker Priester macht einen exzellenten Jiggly-Dance im Rhythmus der Musik. Entweder das oder ein gallertartiger Würfel ist auf die Tanzfläche.",
]},
{"title": "d6 Fragwürdige Getränke", "id":"d6questionabledrinks", "roll":[
"Tonight's special cocktail: Pixiewine. Each glass of this crisp, floral-scented wine is served with a pixie.",
"Tonight's special cocktail: Suckerpunch. Each glass of this potent purple-red punch has several small writhing tentacles that reach out of the glass to attach to your face with their suckers. It actually feels kind of nice.",
"Tonight's special: Bring-Your-Own-Horn. Bring the horn of your favorite beast or monstrous humanoid (any size!), and we'll fill it with cheap ale or wine for 2 cp.",
"Tonight's special cocktail: Mindbomb. It's made with absinthe and explosive powder.",
"Tonight's special cocktail: Fireball. Served by wizards of 5th level or higher.",
"Tonight's special cocktail: Stonebones. A powerful rum cocktail made with powder gorgon horn and basilisk eye. It's only partial paralysis.",
]},
{"title": "d20 Komplotte, Unfug und Ärger", "id":"d20schemesmischiefandtrouble", "roll":[
"Eine Gruppe von Straßenräubern ist betrunken und ein wenig zu laut, wenn sie über die Karawane sprechen, die sie außerhalb der Stadt geplündert haben und was sie mit ihren Anteilen tun sollen.",
"Abenteurer mbewegen einen von einem Basilisken zu Stein verwandelten Begleiter in die Bar. Der Rouge versucht, ihn als Hutablage an den Barkeeper zu verpfänden. Der Barkeeper denkt darüber nach.",
"Der Barkeeper hat keine Tassen mehr, weil ein Zauberer in einer Ecke über einem mit Tassen bedeckten Tisch ohnmächtig geworden ist. Sein betrunkener Vertrauter greift jeden an, der sich dem Tisch nähert, und verhindert so die Wiederverwendung der Tassen.",
"Ein Feendrachen ist in den Sparren ohnmächtig. An einer Klaue hängt ein Spitzenbüstenhalter.",
"Ein fetter Gnom verkauft stinkenden Käse aus einem Weidenkorb.",
"Ein betrunkener Betrachter wird mürrisch. Oder wird verspielt, es ist schwer zu sagen.",
"Zwei Schmuggler sprechen in einer niesche, bevor sie anfangen zu streiten. Sie schießen sich gegenseitig an, einer von ihnen stirbt. Niemand ist völlig sicher, wer zuerst geschossen hat.",
"Ein Mann sitzt alleine und spricht relativ normal zu dem leeren Platz gegenüber von ihm, bevor er wütend ruft.",
"Ein Paar Ratfolk wird von ein paar betrunkenen Gönnern belästigt. Sie beleidigen nicht zurück.",
"Ein Kind versucht, einen unbeliebten Gruppenmitglied einen Streich zu spielen. Er ist nah dran, aber du erkennst ein Problem in seinem Plan, das du lösen kannst.",
"Es ist Ladies Night! Und diese Bar ist ein Wurstfest.",
"Ein Nekromant führt einen stolpernden betrunkenen Gönner aus der Tür.",
"Der Rausschmeißer hackt mit seinem Morgenstern auf einen widerspenstigen Goblin ein. Keinen interessiert es, weil die Party rockt.",
"Ein Messer spaltet den Volltreffer des laufenden Dartspiels der Elfen. Die Elfen ziehen Bögen und fangen an, alle zu erschießen.",
"Ein Illithid erziehlt ein Vermögen mit einem Stapel Tarotkarten auf einem umgestürzten Fass vor der Tür. Manche sagen, es ist Betrug, weil er Gedanken lesen kann, aber ich sage es betrügt, weil er den Verstand essen kann.",
"Ein Otyugh macht wieder ein Durcheinander auf dem Klo.",
"Ein Waldelf dominiert die Dartscheibe und verdankt der Menge um ihn herum bereits eine beachtliche Summe Geld.",
"Die Taverne ist voll von Gruppen von Touristen, die alle ein einzelnes Plakat am schwarzen Brett bewundern. Bald merkt man, dass sie alle Abenteuergruppen sind, und es gibt nur noch einen Job. Sie alle beginnen die Tür zu öffnen, um der erste zu sein, um den Job zu erfüllen. ",
"Eine große Kuh sitzt an einem Ende, und ein Zauberer murmelt ´Ich bin mir sicher, dass das noch nie passiert ist, Babe´ in ihr Ohr.",
"Der Schankraum ist von Wand zu Wand voll. Ein königlicher Zwerg, der mit einer großen Kette geschmückt ist, steht auf der Bar und kauft alle Getränke und predigt zu Gundar, des großen Gottes des Feierns.",
]},
{"title": "d40 Du hast von dieser Taverne schon vorher gehört / hier gegessen weil...", "id":"d40youhaveheardofthistavernbeforeeatentherebeforebecause", "roll":[
"Sie eine schlechte Kirschtorte machen",
"Sie ihre Pierogies wirklich gut sind",
"Sie die Borscht-Hauptstadt der Welt sind",
"Ihr Ruf für Gołąbkis konkurrenzlos ist",
"Sie Speck auf alles legen",
"Sie eine heiße Kellnerin haben",
"Sie immer freie Pferdeparkplätze haben",
"Der Karottenbrei ein Traum ist",
"Niemand weiß wo sie ist, weswegen es normalerweise ruhig ist.",
"Sie länger offen hat als alles andere in der Stadt.",
"Niemand außer Abenteurern mutig genug ist, um an einem Ort zu essen, der unter der lightning rail gebaut wurde, so dass die Kaufleute und  Städter fern bleiben.",
"Sie kaufen das Fleisch, das du mitbringst und kochen es frisch.",
"Sie haben die anderen Geschäfte rücksichtslos aus der Stadt vertrieben und du verhungerst.",
"Es leckere Desserts gibt. Der Käsekuchen ist ein Traum!",
"Die Bierauswahl gut ist. Sie haben eine große Auswahl an Ales.",
"Es Homebrew-Bier gibt. Sie brauen ihren eigenen Drachen-Stout im Haus!",
"Das Fleisch gut ist. Der Besitzer ist ein Jäger, der jeden Tag in den Wald geht, um den Hauptbraten zu fangen und zu töten.",
"Es tierisch eingerichtet ist. Die Wände sind mit Pelzen, Geweihen und Tierköpfen bedeckt.",
"Es schönes Dekor gibt. Die Kabinen sind durch wunderschöne Spitzenvorhänge getrennt und ein angenehmer Duft von Weihrauch durchdringt die Luft.",
"Heroische Geschichten erzählt werden. Der Besitzer tötete einen Drachen.",
"Traurige Geschichten erzählt werden. Der Barkeeper ist eine beeindruckende Edelfrau, die mit dem armen Sohn einer Hure durchgebrannt ist, der diesen Ort besaß, bevor er starb.",
"Das Sexappeal jeden anzieht. Die Bardamen tragen tief ausgeschnittene Blusen und / oder enge Röcke.",
"Es freundlichen Service gibt. Die Bardamen sind sehr freundlich.",
"Glücksspiel gefördert wird. Das Würfelspiel ist High-Stakes.",
"Die Mitarbeiter besonders sind. Der Türsteher ist ein Halb-Troll.",
"Es beeindruckende Mitarbeiter gibt. Der Türsteher hat ein Drachen-Tattoo auf seinem Gesicht.",
"Es High-End-Weine gibt. Ihre Weine kommen von einer unaussprechlichen Elfeninsel.",
"Es magische Getränke gibt. Der Barkeeper ist ein alchemistischer Zauberer, der Liebestränke, Schlaftränke und Schnurrbart-Tonika serviert. (Manche mögen argumentieren, dass ein gutes Schnurrbartonikum der ganze Liebestrank ist, den man braucht.)",
"Die Unterhaltung gut ist. Der Barkeeper spielt hier ein schönes Klavier.",
"Es viele Dekorationen gibt, sie haben Trophäen von überall.",
"Es viele Bewertungen gibt, ein bisschen Unsinn mit einem Stift auf Papier und diesen neumodischen Worten geschrieben.",
"Der Adel es mag, die High Society Typen mögen es.",
"Der Eintritt ein Statussymbol ist.",
"Es der Ort ist, wo du hingehen musst, um Problemlöser zu finden.",
"Es warm ist, die Wände halten die Kälte und den Schnee auf magische Weise fern.",
"Die Zwerge es bauten.",
"Es einmal eine Bibliothek war und es gibt eine riesige Auswahl an Büchern zu lesen.",
"Es einmal ein Tempel war und der halb tote Gott, der dort angebetet wurde, immer noch gelegentlich versucht die Beschmutzer zu bestrafen, manchmal mit mehr Erfolg als sonst.",
"Sie eine großzügige Kreditpolitik verfolgen",
"Es ein exotischer Ort ist, und Spelljammer kommen manchmal vorbei und bringen Schmuckstücke aus allen Ebenen mit.",
]},


// end of settlements

];
