// magic.js
// translation by Gov. Tarkin
//

top.magic = [



   {"title": "d4 Jede Seitentasche kann ___ Pfund Materialien enthalten...", "id":"d4eachsidepouchcanhold___poundsofmaterial_dimensonshaversack", "roll":[
  "10",
  "15",
  "20",
  "25",   ]},
   {"title": "d4 Oder Materialien die größer sind als ___ Kubikfuß...", "id":"d4notexceedingavolumeof___cubicfeet_dimensonshaversack", "roll":[
  "1",
  "1/2",
  "2",
  "2 1/2",   ]},
   {"title": "d6 Die große zentrale Tasche kann ___ Pfund Materialien enthalten...", "id":"d6thelargecentralpouchcanholdupto___poundsofmaterial_dimensonshaversack", "roll":[
  "50",
  "60",
  "70",
  "80",
  "90",
  "100",   ]},
   {"title": "d6 Oder ___ Kubikfuß...", "id":"d6or___cubicfeet_dimensonshaversack", "roll":[
  "6 1/2",
  "7",
  "7 1/2",
  "8",
  "8 1/2",
  "9",   ]},
   {"title": "d4 Der Tisch wiegt immer ___ Pfund unabhängig von seinem Inhalt...", "id":"d4thehaversackalwaysweighs___poundregardlessofitscontents_dimensonshaversack", "roll":[
  "2 1/2",
  "5",
  "7 1/2",
  "10",   ]},

   {"title": "d6 Auf der Außenseite ist die Tasche grob ___ Fuß im Durchmesser von der Öffnung aus...", "id":"d6ontheoutsidethebagisroughly___feetindiameteratthemouth_dimensions", "roll":[
  "1",
  "1 1/2",
  "2",
  "2 1/2",
  "3",
  "3/12",   ]},
   {"title": "d6 und ___ Fuß tief...", "id":"d6and___feetdeep_dimensions", "roll":[
  "2 1/2",
  "3",
  "3 1/2",
  "4",
  "4 1/2",
  "5",   ]},
   {"title": "d6 Es kann bis zu ___ Pfund aufbewahren...", "id":"d6itcanholdupto___pounds_dimensions", "roll":[
  "200",
  "350",
  "500",
  "650",
  "800",
  "1000",   ]},
   {"title": "d4 Wobei ein Volumen von ___ Kubikfuß nicht überschritten wird...", "id":"d4notexceedingavolumeof___cubicfeet_dimensions", "roll":[
  "32",
  "48",
  "64",
  "80",   ]},
   {"title": "d4 Die Tasche wiegt immer ___ Pfund unabhängig von seinem Inhalt", "id":"d4thebagalwaysweighs___poundsregardlessofitscontents_dimensions", "roll":[
  "10",
  "15",
  "20",
  "25",   ]},

 {"title": "d20 Der Artikel scheint gemacht zu sein aus...", "id":"d20theitemappearstobemadeof_bagofholding", "roll":[
"Rauen Leder",
"Feinen Leder",
"Hanf oder Leinen",
"Schweren Papier",
"Seide",
"Sackleinen",
"Einen konservierten Organ",
"Spinnenseide",
"Mithrilkette",
"Menschlichen Haar",
"Segeltuch",
"Drachenschuppen",
"Gewebten Reben",
"Gepressten Blättern",
"Einen alten Dudelsack",
"Einen menschlichen (oder von einer anderen PC-Rasse) Schädel und / oder Brustkorb",
"Lebenden Fleisch",
"Goldtuch",
"Silbertuch",
"Samt",]},
 {"title": "d10 Die Herkunft der Tasche ist ___ ...", "id":"d10theitemisof___origin_bagofholding", "roll":[
"Höllisch",
"Himmlisch",
"Geheimnisvoll",
"Göttlich",
"Von einer anderen Ebene",
"Interdimensional",
"Natürlich",
"Banal",
"Wunderhaft",
"Unbekannt",   ]},
 {"title": "d10 Die Tasche...", "id":"d10theitem_bagofholding", "roll":[
"Riecht komisch",
"Ist mit Briefmarken / Siegeln bedeckt",
"Ist mit einem verzierten Muster geprägt oder bestickt",
"Leuchtet im Dunkeln",
"Hat eine offensichtliche Reparatur hintersich",
"Besteht aus zwei verschiedenen Materialien (Würfel zweimal auf der 'scheint gemacht zu sein aus...' Tabelle zu sein)",
"Hat mehr als ein Fach (Roll die Innenmaße für den Hauptbeutel zweimal, ansonsten wird es wie eine Tasche behandelt)",
"Erfordert Zustimmung um es zu benutzen",
"Teilt 1d8 Knüppelschaden",
"Ist immer offen",]},
 {"title": "d20 Dinge, die in dem Gegenstand gelegt werden...", "id":"d20thingsthatareplacedintotheitem_bagofholding", "roll":[
"Werden mit der Zeit größer",
"Werden im Laufe der Zeit schrumpfen",
"Werden im Laufe der Zeit gereinigt",
"Werden im Laufe der Zeit verschmutzt",
"Werden im Laufe der Zeit rosten",
"Werden unnatürlich schnell altern",
"Werden unnatürlich langsam altern",
"Werden verrotten",
"Werden erhalten",
"Sind heiß, wenn sie berührt werden",
"Sind kühl, wenn sie berührt werden",
"Langsam empfindsam werden",
"Langsam Intelligenz verlieren",
"Werden die Farbe ändern",
"Werden Farbe verlieren",
"Sind gesegnet",
"Sind verflucht",
"Scheinen in der Dunkelheit",
"Absorbieren Licht",
"Würfel zweimal",]},
 {"title": "d10 Der vorherige Besitzer des Artikels...", "id":"d10theitemspreviousowner_bagofholding", "roll":[
"Die Tasche hatte keinen Vorbesitzer",
"Warf es weg",
"Verkaufte es",
"Hat es beim Glücksspiel verloren",
"Wurde bestohlen",
"Gab es einem Freund",
"Ist plötzlich gestorben",
"Sucht danach",
"Weiß, wo es ist",
"Ist das Große Böse",]},
 {"title": "d20 Startidee für ein Abenteuer: Herzliche Glückwünsche! Du hast einen [dreidimensionalen Gegenstand hier einfügen] gefunden! Es beinhaltet...", "id":"d20adventureseedcongratulations!youfoundan[insertextradimensionalitemhere]!itcontains_bagofholding", "roll":[
"Nichts",
"60 Fuss Seil",
"Ein Käserad",
"Einen Bündel getrockneter Blätter",
"Einen mumifizierten Vogel",
"Einen Siegelring",
"Dreizehn zufällige Spielkarten",
"Eine zerbrochene Flasche Whistle",
"Ein Paar falsche Zähne",
"Ein I.O.U.",
"Eine ausgetrocknete selbstfärbende Feder",
"Eine Packung Samen",
"Eine Broschüre von einer Bank",
"Eine Strickmütze",
"Eine Handvoll Diamanten",
"Ein einziger Kinderschuh",
"Eine Menge Diebeswerkzeuge",
"Eine halbvolle Thermosflasche mit warmen Tee",
"Die Überreste des vorherigen Besitzers des Gegenstandes",
"Einen anderen [fügen Sie einen dreidimensionalen Gegenstand hier ein]",]},
 {"title": "d20 Startidee für ein Abenteuer: Du liebst deinen [Generierten mehrdimensionalen Gegenstand]! Es ist großartig! Aber plötzlich...", "id":"d20adventureseedyouloveyour[genericextradimensionaldoodad]!itsgreat!butsuddenly_bagofholding", "roll":[
"Beginnt der Gegenstand Rauch zu produzieren, wenn er offen ist",
"Haben sie eine Chance von 25%, einen lebenden Fisch aus dem Gegenstand herauszuziehen, anstatt nach dem was Sie suchen",
"Alles Gold im Gegenstand wird sofort zu Ton",
"Alles Gold im Gegenstand wird sofort verdoppelt",
"Im Vertrag erscheint ein Vertrag mit der Behauptung, dass Ihr Mietvertrag abgelaufen ist und alle Inhalte des Gegenstands an den Vermieter gehen werden, sobald Sie diesen Satz gelesen haben",
"Erscheinen Rationen beim jeden Sonnenaufgang im Gegenstand, und wenn sie nicht konsumiert werden, verschwinden sie jeden Sonnenuntergang",
"Fängt der Gegenstand an, helles Licht von der geöffneten Öffnung zu emittieren",
"Erscheint ein schwarzer Dolch und eine Namensliste im Gegenstand",
"Erscheint ein Liebesbrief von einem NPC, den du in der Vergangenheit gesehen hast, in dem Gegenstand",
"Erscheint ein juwelenbesetzter mechanischer Vogel im Gegenstand. Wenn er verwundet wird, zaubert er einmal pro Tag Schlaf (als Zauberspruch der ersten Stufe), betrifft aber nur Kreaturen, die von dem DM ausgewählt wurden",
"Beginnt eine kühle Briese durch den Gegenstand fließen, und Kreaturen, die in dem Gegenstand liegen, ersticken nicht",
"Wenn der Gegenstand geworfen oder fallen gelassen wird, beginnt der Gegenstand so zu fallen, so dass er auf etwas Bestimmtes zeigt",
"Erscheint eine Kristallkugel in dem Gegenstand, und wenn sie berührt wird, ist sie mit dem Bild eines suchenden Auges gefüllt",
"Erscheint eine lange, dünne Nadel im Gegenstand, mit der man die Außenmaße des Gegenstandes erweitern oder verändern kann",
"Erscheint ein Buch in dem Gegenstand, der einen Zauber der ersten Stufe enthält, den du nicht kennst. Dieser Zauberspruch kann einmal am Tag gewirkt werden.",
"Erscheint ein Satz von zwei sechsseitigen Würfeln in dem Gegenstand. Einmal pro Tag, als eine Aktion können sie gewürfelt werden, und wenn ihr Wert gleich neun oder größer ist, können Sie sofort eine zusätzliche Runde machen",
"Beginnt der Gegenstand jedes Mal, wenn er offen ist, ein unnachahmliches schrilles Quietschen zu machen",
"Haben sich die Innenmaße des Gegenstands geändert, und Sie müssen sie neu auswürfeln",
"Wurde der Inhalt des Gegenstands mit dem einer anderen Pocket-Dimension getauscht",
"Hörst du Stimmen aus deinem Gegenstand, und du bist überrascht, dass zwei Halblinge den Inhalt deines Gegenstandes durchstöbern",]},
 {"title": "d20 Startidee für ein Abenteuer: Du gehst eine Wald- / Wüsten- / Stadtstraße entlang, als aus dem Nichts!...", "id":"d20yourewalkingdownaforestdesertcityroadwhenoutofnowhere!_bagofholding", "roll":[
"Ein Nimmervoller Beutel in deiner Hand erscheint",
"Hewards praktischer Rucksack auf deinem Rücken erscheint",
"Ein tragbares Loch auf dem Boden erscheint",
"Du auf eine Tasche von der Größe eines Pferdes stößt",
"Du auf eine Tasche von der Größe einer Bremse stößt",
"Du eine Stimme sagen hörst: Willst du einen Nimmervollen Beutel kaufen?",
"Du eine Stimme sagen hörst: Wenn du einen Nimmervollen Beutel zum Verkaufen hast, werde ich dich reichlich entlohnen ...'",
"Eine verzweifelte Person dich fragt, ob du ihren Nimmervollen Beutel gesehen hast",
"Ein flüchtendes Individuum dir einen Nimmervollen Beutel in deine Hände drückt.",
"Eine kleine Kreatur mit dir Blickkontakt aufnimmt, und dann in einen Nimmervollen Beutel verschwindet",
"Eine verstörte Person droht (Was sie behaupten ist einer) einen Nimmervollen Beutel in (Was sie behaupten ist ein) ein tragbares Loch zu werfen",
"Eine gute Person nicht versteht, warum sie ihr tragbares Loch nicht in einen Nimmervollen Beutel stecken kann",
"Eine ausgemergelte Person erscheint und behauptet, ein Mitglied deiner Gruppe habe sie in einem tragbaren Loch gefangen gehalten",
"Ein Mitglied Ihrer Gruppe aus dem Nichts erscheint und behauptet, dass ein Doppelgänger sie in einem tragbaren Loch gefangen gehalten hat",
"Ein Händler versucht dir die Pläne für eine Pfeilspitze der totalen Zerstörung zu verkaufen",
"Sie auf eine Gedenktafel stoßen, die an die Detonation einer Pfeilspitze der totalen Zerstörung erinnert",
"Sie auf einen abgenutzten blau lackierten Holzschrank mit einem tragbaren Loch an einer der Innenwände stoßen",
"Eine Person, die behauptet, Heward zu sein, möchte, dass Sie einen Fragebogen über Tornister und ihre relativen Handlichkeiten ausfüllen",
"Eine Person, die behauptet, Heward zu sein, dich bittet, eine neue Erfindung zu testen, die er Hewards Hübscher Hut nennt",
"Du auf etwas stößt, von dem du glaubst, dass es eine Sackgasse ist, aber es tatsächlich ein Mimik ist. Oh nein!",]},
 {"title": "d6 Startidee für ein Abenteuer: Du stößt auf einen Nimmervollen Beutel, der die Größe eines Hauses hat. Die Eröffnung ist...", "id":"d6adventureseedyoucomeacrossabagofholdingthesizeofahousetheopeningis_bagofholding", "roll":[
"offen, und du kannst nach innen sehen",
"offen, aber dunkel",
"offen, aber von einem großen Tor oder einer Tür versperrt",
"offen, aber durch eine Mauer oder Felsen verschlossen",
"geschlossen, aber leicht zu öffnen",
"geschlossen und nicht leicht zu öffnen",]},
 {"title": "d20 Startidee für ein Abenteuer: Das Innere der Tasche ist...", "id":"d20adventureseedtheinsideofthebagis_bagofholding", "roll":[
"Ein Haus, komplett mit Schornstein, Veranda und Keller. Es ist innen ein wenig größer als außen",
"voll mit Rationen, Münzen und anderen weltlichen Dingen, aber viel größeren als du es gewohnt bist zu sehen",
"voll mit Rationen, Münzen und gewöhnlichen magischen Gegenständen, aber viel größeren als du es gewohnt bist zu sehen",
"der Eingang zu einer Reihe von Höhlen und Höhlen, die sonst in der Gegend, in der du dich befindest, unmöglich wären",
"eine Einrichtung für die Pflege und Wartung von Taschendimensionen. Das Innere ist scheinbar unendlich, aber die Öffnung ist immer nur ein paar Schritte entfernt",
"ein kleines Königreich. Der Eingang wird von Personen in schwerer Rüstung bewacht",
"ein großer Laden",
"scheinbar leer",
"scheinbar voll, aber alles ist eigentlich eine Illusion",
"innen kleiner als außen",
"ein anderes Universum, scheinbar von gleicher Größe und Komplexität wie das, aus dem du gekommen bist",
"ein anderes Universum, aber alles ist etwas kleiner als in dem, aus dem du gekommen bist",
"ein anderes Universum, aber alles ist etwas größer als das, in dem du gekommen bist",
"ein anderes Universum, aber alles ist völlig unverhältnismäßig",
"voll von Dinosauriern, Sümpfen und Palmen",
"ein trockenes Vakuum. In der Ferne kann man Sterne, Planeten und endlose Dunkelheit sehen",
"eine Akademie",
"Eine einsame Insel in einem weiten Meer",
"ein kunstvoll verziertes Schlafzimmer",
"eine voll ausgestattete Folterkammer",]},


   {"title": "d20 Die magische Krankheit verursacht...", "id":"d20themagicaldiseaseisassociatedwith_magicalmaladies", "roll":[
  "Ausrottung von Ungeziefer.",
  "Dämonischen oder gespenstische Besitzergreifung.",
  "Den Wunsch, humanoides Fleisch zu konsumieren.",
  "Den Wunsch, Steine ​​oder Dreck zu konsumieren.",
  "Den Wunsch, Pixies und Geister zu konsumieren.",
  "Den Wunsch, ein tiefes Loch zu graben.",
  "Den Wunsch, eine riesige Mauer zu bauen.",
  "Die Übernahme der Persönlichkeit eines längst verstorbenen, bekannten Zauberers .",
  "Allmählich die Verwandlung zu einem wilden Biest.",
  "Allmählich die Verwandlungzu einer Pfütze.",
  "Das Nachahmen des Verhaltens einer gemeinen Bestie.",
  "Den Verlust der Fähigkeit zu reden.",
  "Einen anhaltenden Effekt des Zaubers der Verwirrung.",
  "Lilane oder grüne Flecken auf der Haut.",
  "Rasantes Wachstum der Gesichtsbehaarung.",
  "Rasantes Wachstum von Fingernägeln oder Zähnen.",
  "Rasantes Haarwachstum.",
  "Unkontrollierbare Anfälle des Lachens oder Weinens.",
  "Unkontrollierbares Singen oder Tanzen.",
  "Überaktive Libido.",]},



];
